/*
Copyright (c) 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Written by the KLR Contributors (https://github.com/leanprover/KLR)
*/
#pragma once

// This file is automatically generated from KLR.
// Manual edits to this file will be overwritten.

#include "klir_common.hpp"


namespace klr {

// KLR.Core Abstract Syntax











struct Pos final {
  Nat line;
  Nat column;
  Option<Nat> lineEnd;
  Option<Nat> columnEnd;
};

enum class Memory {
hbm = 1,
sbuf,
pmem,
reg,
};

enum class Dtype {
bfloat16 = 1,
float8e3,
float8e4,
float8e5,
float16,
float32,
float32r,
int8,
int16,
int64,
int32,
uint8,
uint16,
uint32,
uint64,
};

struct Shape final {
  Nat parDim;
  List<Nat> freeDims;
};

struct Address final {
  Memory memory;
  Nat parSize;
  Nat freeSize;
  Option<Nat> parOffset;
  Option<Nat> freeOffset;
};

struct TensorName final {
  String name;
  Dtype dtype;
  Ptr<Shape> shape;
  Ptr<Address> address;
  Nat freeElements;
  Prop parWF;
  Prop freeWF;
};

struct Slice final {
  Nat l;
  Nat u;
  Int step;
  Prop wf;
};

struct Index {
enum class Tag {
coord = 1,
slice,
};
  Tag tag;
  Index(Tag tag) : tag(tag) {}
};

struct IndexCoordWrapper final : Index {
Nat e;
 IndexCoordWrapper() : Index(Tag::coord) {}
};

struct IndexSliceWrapper final : Index {
Ptr<Slice> slice;
 IndexSliceWrapper() : Index(Tag::slice) {}
};

struct AccessBasic final {
  Ptr<TensorName> tensor;
  List<Ptr<Index>> indexes;
  Prop lenWF;
};

struct APPair final {
  Int step;
  Nat num;
};

struct AccessPattern final {
  Ptr<TensorName> tensor;
  Nat parNum;
  List<Ptr<APPair>> freePattern;
  Nat offset;
};

struct Access {
enum class Tag {
simple = 1,
basic,
pattern,
};
  Tag tag;
  Access(Tag tag) : tag(tag) {}
};

struct AccessSimpleWrapper final : Access {
Ptr<TensorName> tensor;
 AccessSimpleWrapper() : Access(Tag::simple) {}
};

struct AccessBasicWrapper final : Access {
Ptr<AccessBasic> access;
 AccessBasicWrapper() : Access(Tag::basic) {}
};

struct AccessPatternWrapper final : Access {
Ptr<AccessPattern> access;
 AccessPatternWrapper() : Access(Tag::pattern) {}
};

struct TensorHbm final {
  String name;
  Dtype dtype;
  Nat address;
  List<Ptr<APPair>> dims;
};

enum class ParQuadrant {
par0 = 1,
par32,
par64,
par96,
};

struct TensorSram final {
  String name;
  Dtype dtype;
  ParQuadrant parQuadrant;
  Nat parDim;
  Nat freeOffset;
  List<Ptr<APPair>> freePattern;
};

struct TensorRef {
enum class Tag {
abstract = 1,
sbuf,
psum,
hbm,
reg,
};
  Tag tag;
  TensorRef(Tag tag) : tag(tag) {}
};

struct TensorRefAbstractWrapper final : TensorRef {
Ptr<Access> access;
 TensorRefAbstractWrapper() : TensorRef(Tag::abstract) {}
};

struct TensorRefSbufWrapper final : TensorRef {
Ptr<TensorSram> view;
 TensorRefSbufWrapper() : TensorRef(Tag::sbuf) {}
};

struct TensorRefPsumWrapper final : TensorRef {
Ptr<TensorSram> view;
 TensorRefPsumWrapper() : TensorRef(Tag::psum) {}
};

struct TensorRefHbmWrapper final : TensorRef {
Ptr<TensorHbm> view;
 TensorRefHbmWrapper() : TensorRef(Tag::hbm) {}
};

struct TensorRefRegisterWrapper final : TensorRef {
Nat reg;
 TensorRefRegisterWrapper() : TensorRef(Tag::reg) {}
};

enum class Engine {
unassigned = 1,
act,
dma,
dve,
pe,
pool,
sp,
};

struct Immediate {
enum class Tag {
reg = 1,
pointer,
int32,
float32,
};
  Tag tag;
  Immediate(Tag tag) : tag(tag) {}
};

struct ImmediateRegisterWrapper final : Immediate {
Nat reg;
 ImmediateRegisterWrapper() : Immediate(Tag::reg) {}
};

struct ImmediatePointerWrapper final : Immediate {
 ImmediatePointerWrapper() : Immediate(Tag::pointer) {}
};

struct ImmediateIntWrapper final : Immediate {
Int i;
 ImmediateIntWrapper() : Immediate(Tag::int32) {}
};

struct ImmediateFloatWrapper final : Immediate {
Float f;
 ImmediateFloatWrapper() : Immediate(Tag::float32) {}
};

struct ActivationImm {
enum class Tag {
reg = 1,
pointer,
float32,
};
  Tag tag;
  ActivationImm(Tag tag) : tag(tag) {}
};

struct ActivationImmRegisterWrapper final : ActivationImm {
Nat reg;
 ActivationImmRegisterWrapper() : ActivationImm(Tag::reg) {}
};

struct ActivationImmPointerWrapper final : ActivationImm {
 ActivationImmPointerWrapper() : ActivationImm(Tag::pointer) {}
};

struct ActivationImmFloatWrapper final : ActivationImm {
Float f;
 ActivationImmFloatWrapper() : ActivationImm(Tag::float32) {}
};

struct Scale {
enum class Tag {
imm = 1,
tensor,
};
  Tag tag;
  Scale(Tag tag) : tag(tag) {}
};

struct ScaleImmWrapper final : Scale {
Ptr<Immediate> i;
 ScaleImmWrapper() : Scale(Tag::imm) {}
};

struct ScaleTensorWrapper final : Scale {
Ptr<TensorRef> t;
 ScaleTensorWrapper() : Scale(Tag::tensor) {}
};

struct Scale {
enum class Tag {
imm = 1,
tensor,
};
  Tag tag;
  Scale(Tag tag) : tag(tag) {}
};

struct ScaleImmWrapper final : Scale {
Ptr<Immediate> i;
 ScaleImmWrapper() : Scale(Tag::imm) {}
};

struct ScaleTensorWrapper final : Scale {
Ptr<TensorRef> t;
 ScaleTensorWrapper() : Scale(Tag::tensor) {}
};

struct Axis {
enum class Tag {
ax = 1,
axs,
};
  Tag tag;
  Axis(Tag tag) : tag(tag) {}
};

struct AxisAxWrapper final : Axis {
Int ax;
 AxisAxWrapper() : Axis(Tag::ax) {}
};

struct AxisAxsWrapper final : Axis {
List<Int> axs;
 AxisAxsWrapper() : Axis(Tag::axs) {}
};

struct Operand {
enum class Tag {
imm = 1,
tile,
};
  Tag tag;
  Operand(Tag tag) : tag(tag) {}
};

struct OperandImmWrapper final : Operand {
Ptr<Immediate> i;
 OperandImmWrapper() : Operand(Tag::imm) {}
};

struct OperandTileWrapper final : Operand {
Ptr<TensorRef> t;
 OperandTileWrapper() : Operand(Tag::tile) {}
};

struct DataPattern final {
  Nat offset;
  List<Ptr<APPair>> pattern;
};

enum class AluOp {
abs = 1,
add,
arith_shift_left,
arith_shift_right,
average,
bitwise_and,
bitwise_not,
bitwise_or,
bitwise_xor,
bypass,
divide,
is_equal,
is_ge,
is_gt,
is_le,
is_lt,
logical_and,
logical_or,
logical_shift_left,
logical_shift_right,
logical_xor,
max,
min,
mod,
mult,
not_equal,
pow,
rsqrt,
subtract,
};

enum class DropoutThresholdType {
DropRate = 1,
KeepRate,
};

enum class AccumCmd {
Idle = 1,
Zero,
Accumulate,
ZeroAccumulate,
LoadAccumulate,
};

enum class ActivationFunc {
abs = 1,
arctan,
copy,
erf,
erf_dx,
exp,
gelu,
gelu_apprx_tanh,
gelu_dx,
log,
mish,
reciprocal,
relu,
rsqrt,
sigmoid,
sign,
silu,
silu_dx,
sin,
softplus,
sqrt,
square,
tanh,
};

enum class AffineSelectCmp {
GreaterThan = 1,
GreaterThanEq,
Eq,
NotEq,
};

enum class DgeComputeOp {
none = 1,
add,
};

struct DmaBounds {
enum class Tag {
disable = 1,
enable,
reg,
};
  Tag tag;
  DmaBounds(Tag tag) : tag(tag) {}
};

struct DmaBoundsDisableWrapper final : DmaBounds {
 DmaBoundsDisableWrapper() : DmaBounds(Tag::disable) {}
};

struct DmaBoundsEnableWrapper final : DmaBounds {
 DmaBoundsEnableWrapper() : DmaBounds(Tag::enable) {}
};

struct DmaBoundsRegWrapper final : DmaBounds {
Nat reg;
 DmaBoundsRegWrapper() : DmaBounds(Tag::reg) {}
};

enum class MatmulGroupElement {
first = 1,
middle,
last,
whole,
};

struct IndexMissBehavior {
enum class Tag {
imm = 1,
skip,
};
  Tag tag;
  IndexMissBehavior(Tag tag) : tag(tag) {}
};

struct IndexMissBehaviorImmWrapper final : IndexMissBehavior {
Ptr<Immediate> value;
 IndexMissBehaviorImmWrapper() : IndexMissBehavior(Tag::imm) {}
};

struct IndexMissBehaviorSkipWrapper final : IndexMissBehavior {
 IndexMissBehaviorSkipWrapper() : IndexMissBehavior(Tag::skip) {}
};

enum class TensorScalarReverseOps {
none = 1,
first,
second,
both,
};

enum class TensorSubDim {
X = 1,
XY,
XYZ,
XYZW,
};

struct Dropout final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  DropoutThresholdType thresholdType;
  Ptr<Operand> threshold;
  Option<Dtype> dtype;
};

struct Activate final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  AccumCmd accumulatorCmd;
  ActivationFunc activationFunc;
  Ptr<Immediate> scale;
  Ptr<Immediate> bias;
  Option<AluOp> reduceOp;
  Option<Ptr<TensorRef>> reduceRes;
};

struct AffineSelect final {
  Ptr<TensorRef> dst;
  Ptr<DataPattern> pred;
  Ptr<TensorRef> onTrueTile;
  Ptr<Immediate> onFalseValue;
  Option<Dtype> dtype;
};

struct DmaCopy final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  DgeComputeOp compute_op;
  Ptr<DmaBounds> oobMode;
  Nat dgeMode;
};

struct DmaTranspose final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
};

struct Transpose final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Option<Dtype> dtype;
  Engine engine;
};

struct LoadMaskRegister final {
  Nat regNum;
};

struct Shuffle final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  List<Ptr<Immediate>> shuffleMask;
  Option<Dtype> dtype;
};

struct MemSet final {
  Ptr<TensorRef> dst;
  Ptr<Immediate> value;
  Nat count;
  Dtype dtype;
  Engine engine;
};

struct Iota final {
  Ptr<TensorRef> dst;
  Ptr<DataPattern> pattern;
  Option<Dtype> dtype;
};

struct LoadStationary final {
  Ptr<TensorRef> src;
  Bool isTranspose;
};

struct MatMul final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> moving;
  MatmulGroupElement psumAccumulateFlag;
};

struct LocalGather final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Ptr<TensorRef> index;
  Ptr<Immediate> numElemPerIdx;
  Option<Ptr<Immediate>> numValidIndicies;
};

struct RangeSelect final {
  Ptr<TensorRef> dst;
  AccumCmd reduceCommand;
  Option<Ptr<TensorRef>> reduceRes;
  Option<AluOp> reduceOp;
  AluOp compOp0;
  AluOp compOp1;
  Ptr<TensorRef> bound0;
  Ptr<TensorRef> bound1;
  Ptr<Immediate> rangeStart;
  Ptr<TensorRef> onTrueTile;
  Ptr<Immediate> onFalseValue;
  Option<Dtype> dtype;
};

struct ScalarTensorTensor final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> data;
  Ptr<Operand> src0;
  Ptr<Operand> src1;
  AluOp op0;
  AluOp op1;
  TensorScalarReverseOps reverseOperands;
  Option<Dtype> dtype;
};

struct CopyPredicated final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Ptr<TensorRef> predicate;
  Option<Dtype> dtype;
  Bool reversePred;
};

struct TensorTensorScan final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src0;
  Ptr<TensorRef> src1;
  AluOp op0;
  AluOp op1;
  TensorScalarReverseOps reverseOperands;
  Ptr<Operand> initial;
  Option<Dtype> dtype;
};

struct MatchValueLoad final {
  Ptr<TensorRef> src;
};

struct FindIndex8 final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Ptr<TensorRef> vals;
  Option<Dtype> dtype;
};

struct MatchReplace8 final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Ptr<TensorRef> vals;
  Ptr<Immediate> replaceValue;
  Option<Ptr<TensorRef>> dstIdx;
  Option<Dtype> dtype;
};

struct Max8 final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Option<Dtype> dtype;
};

struct BatchNormAggregate final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Option<Dtype> dtype;
};

struct BatchNormStats final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Option<Dtype> dtype;
};

struct Reciprocal final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Option<Dtype> dtype;
};

struct Copy final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Option<Dtype> dtype;
  Engine engine;
};

struct TensorReduce final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  AluOp op;
  Ptr<Axis> axis;
  Bool negated;
  Option<Dtype> dtype;
  Bool keepdims;
};

struct TensorScalar final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Ptr<Operand> operand0;
  AluOp op0;
  Option<Ptr<Operand>> operand1;
  Option<AluOp> op1;
  TensorScalarReverseOps reverse;
  Engine engine;
  Option<Dtype> dtype;
};

struct TensorTensor final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src0;
  Ptr<TensorRef> src1;
  AluOp op;
  Option<Dtype> dtype;
  Engine engine;
};

struct NcMatMul final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> stationary;
  Ptr<TensorRef> moving;
  Bool isStationaryOneZero;
  Bool isMovingZero;
  Bool isTranspose;
  List<Nat> tilePosition;
  List<Nat> tileSize;
};

struct NKIOperator {
enum class Tag {
activate = 1,
affineSelect,
batchNormAggregate,
batchNormStats,
copy,
copyPredicated,
dmaCopy,
dmaTranspose,
dropout,
findIndex8,
iota,
loadMaskRegister,
loadStationary,
localGather,
matMul,
matchReplace8,
matchValueLoad,
max8,
memSet,
rangeSelect,
reciprocal,
scalarTensorTensor,
shuffle,
tensorReduce,
tensorScalar,
tensorScalarReduce,
tensorTensor,
tensorTensorScan,
transpose,
ncMatMul,
activationReduce,
tensorPartitionReduce,
};
  Tag tag;
  NKIOperator(Tag tag) : tag(tag) {}
};

struct NKIOperatorActivateWrapper final : NKIOperator {
Ptr<Activate> op;
 NKIOperatorActivateWrapper() : NKIOperator(Tag::activate) {}
};

struct NKIOperatorAffineSelectWrapper final : NKIOperator {
Ptr<AffineSelect> op;
 NKIOperatorAffineSelectWrapper() : NKIOperator(Tag::affineSelect) {}
};

struct NKIOperatorBatchNormAggregateWrapper final : NKIOperator {
Ptr<BatchNormAggregate> op;
 NKIOperatorBatchNormAggregateWrapper() : NKIOperator(Tag::batchNormAggregate) {}
};

struct NKIOperatorBatchNormStatsWrapper final : NKIOperator {
Ptr<BatchNormStats> op;
 NKIOperatorBatchNormStatsWrapper() : NKIOperator(Tag::batchNormStats) {}
};

struct NKIOperatorCopyWrapper final : NKIOperator {
Ptr<Copy> op;
 NKIOperatorCopyWrapper() : NKIOperator(Tag::copy) {}
};

struct NKIOperatorCopyPredicatedWrapper final : NKIOperator {
Ptr<CopyPredicated> op;
 NKIOperatorCopyPredicatedWrapper() : NKIOperator(Tag::copyPredicated) {}
};

struct NKIOperatorDmaCopyWrapper final : NKIOperator {
Ptr<DmaCopy> op;
 NKIOperatorDmaCopyWrapper() : NKIOperator(Tag::dmaCopy) {}
};

struct NKIOperatorDmaTransposeWrapper final : NKIOperator {
Ptr<DmaTranspose> op;
 NKIOperatorDmaTransposeWrapper() : NKIOperator(Tag::dmaTranspose) {}
};

struct NKIOperatorDropoutWrapper final : NKIOperator {
Ptr<Dropout> op;
 NKIOperatorDropoutWrapper() : NKIOperator(Tag::dropout) {}
};

struct NKIOperatorFindIndex8Wrapper final : NKIOperator {
Ptr<FindIndex8> op;
 NKIOperatorFindIndex8Wrapper() : NKIOperator(Tag::findIndex8) {}
};

struct NKIOperatorIotaWrapper final : NKIOperator {
Ptr<Iota> op;
 NKIOperatorIotaWrapper() : NKIOperator(Tag::iota) {}
};

struct NKIOperatorLoadMaskRegisterWrapper final : NKIOperator {
Ptr<LoadMaskRegister> op;
 NKIOperatorLoadMaskRegisterWrapper() : NKIOperator(Tag::loadMaskRegister) {}
};

struct NKIOperatorLoadStationaryWrapper final : NKIOperator {
Ptr<LoadStationary> op;
 NKIOperatorLoadStationaryWrapper() : NKIOperator(Tag::loadStationary) {}
};

struct NKIOperatorLocalGatherWrapper final : NKIOperator {
Ptr<LocalGather> op;
 NKIOperatorLocalGatherWrapper() : NKIOperator(Tag::localGather) {}
};

struct NKIOperatorMatMulWrapper final : NKIOperator {
Ptr<MatMul> op;
 NKIOperatorMatMulWrapper() : NKIOperator(Tag::matMul) {}
};

struct NKIOperatorMatchReplace8Wrapper final : NKIOperator {
Ptr<MatchReplace8> op;
 NKIOperatorMatchReplace8Wrapper() : NKIOperator(Tag::matchReplace8) {}
};

struct NKIOperatorMatchValueLoadWrapper final : NKIOperator {
Ptr<MatchValueLoad> op;
 NKIOperatorMatchValueLoadWrapper() : NKIOperator(Tag::matchValueLoad) {}
};

struct NKIOperatorMax8Wrapper final : NKIOperator {
Ptr<Max8> op;
 NKIOperatorMax8Wrapper() : NKIOperator(Tag::max8) {}
};

struct NKIOperatorMemSetWrapper final : NKIOperator {
Ptr<MemSet> op;
 NKIOperatorMemSetWrapper() : NKIOperator(Tag::memSet) {}
};

struct NKIOperatorRangeSelectWrapper final : NKIOperator {
Ptr<RangeSelect> op;
 NKIOperatorRangeSelectWrapper() : NKIOperator(Tag::rangeSelect) {}
};

struct NKIOperatorReciprocalWrapper final : NKIOperator {
Ptr<Reciprocal> op;
 NKIOperatorReciprocalWrapper() : NKIOperator(Tag::reciprocal) {}
};

struct NKIOperatorScalarTensorTensorWrapper final : NKIOperator {
Ptr<ScalarTensorTensor> op;
 NKIOperatorScalarTensorTensorWrapper() : NKIOperator(Tag::scalarTensorTensor) {}
};

struct NKIOperatorShuffleWrapper final : NKIOperator {
Ptr<Shuffle> op;
 NKIOperatorShuffleWrapper() : NKIOperator(Tag::shuffle) {}
};

struct NKIOperatorTensorReduceWrapper final : NKIOperator {
Ptr<TensorReduce> op;
 NKIOperatorTensorReduceWrapper() : NKIOperator(Tag::tensorReduce) {}
};

struct NKIOperatorTensorScalarWrapper final : NKIOperator {
Ptr<TensorScalar> op;
 NKIOperatorTensorScalarWrapper() : NKIOperator(Tag::tensorScalar) {}
};

struct NKIOperatorTensorScalarReduceWrapper final : NKIOperator {
Ptr<TensorScalarReduce> op;
 NKIOperatorTensorScalarReduceWrapper() : NKIOperator(Tag::tensorScalarReduce) {}
};

struct NKIOperatorTensorTensorWrapper final : NKIOperator {
Ptr<TensorTensor> op;
 NKIOperatorTensorTensorWrapper() : NKIOperator(Tag::tensorTensor) {}
};

struct NKIOperatorTensorTensorScanWrapper final : NKIOperator {
Ptr<TensorTensorScan> op;
 NKIOperatorTensorTensorScanWrapper() : NKIOperator(Tag::tensorTensorScan) {}
};

struct NKIOperatorTransposeWrapper final : NKIOperator {
Ptr<Transpose> op;
 NKIOperatorTransposeWrapper() : NKIOperator(Tag::transpose) {}
};

struct NKIOperatorNcMatMulWrapper final : NKIOperator {
Ptr<NcMatMul> op;
 NKIOperatorNcMatMulWrapper() : NKIOperator(Tag::ncMatMul) {}
};

struct NKIOperatorActivationReduceWrapper final : NKIOperator {
Ptr<ActivationReduce> op;
 NKIOperatorActivationReduceWrapper() : NKIOperator(Tag::activationReduce) {}
};

struct NKIOperatorTensorPartitionReduceWrapper final : NKIOperator {
Ptr<TensorPartitionReduce> op;
 NKIOperatorTensorPartitionReduceWrapper() : NKIOperator(Tag::tensorPartitionReduce) {}
};

struct TensorScalarReduce final {
  Ptr<TensorRef> dst;
  Ptr<TensorRef> src;
  Ptr<Operand> operand0;
  AluOp op0;
  Bool reverse0;
  Option<Dtype> dtype;
  Option<AluOp> reduceOp;
  Ptr<TensorRef> reduceRes;
};

struct ActivationReduce final {
  Ptr<TensorRef> dst;
  ActivationFunc op;
  Ptr<TensorRef> data;
  Option<AluOp> reduceOp;
  Option<Ptr<TensorRef>> reduceRes;
  List<Ptr<Immediate>> bias;
  Ptr<Scale> scale;
  Option<Dtype> dtype;
};

struct TensorPartitionReduce final {
  Ptr<TensorRef> dst;
  AluOp op;
  Ptr<TensorRef> data;
  Option<Dtype> dtype;
};

struct Value {
enum class Tag {
var = 1,
boolean,
int32,
float32,
access,
};
  Tag tag;
  Value(Tag tag) : tag(tag) {}
};

struct ValueVarWrapper final : Value {
String x;
 ValueVarWrapper() : Value(Tag::var) {}
};

struct ValueBoolWrapper final : Value {
Bool value;
 ValueBoolWrapper() : Value(Tag::boolean) {}
};

struct ValueIntWrapper final : Value {
Int value;
 ValueIntWrapper() : Value(Tag::int32) {}
};

struct ValueFloatWrapper final : Value {
Float value;
 ValueFloatWrapper() : Value(Tag::float32) {}
};

struct ValueAccessWrapper final : Value {
Ptr<Access> a;
 ValueAccessWrapper() : Value(Tag::access) {}
};

struct Keyword final {
  String name;
  Ptr<Value> value;
};

struct Expr {
enum class Tag {
value = 1,
call,
};
  Tag tag;
  Expr(Tag tag) : tag(tag) {}
};

struct ExprValueWrapper final : Expr {
Ptr<Value> v;
 ExprValueWrapper() : Expr(Tag::value) {}
};

struct ExprCallWrapper final : Expr {
String f;
List<Ptr<Value>> args;
List<Ptr<Keyword>> kwargs;
 ExprCallWrapper() : Expr(Tag::call) {}
};

struct Stmt {
enum class Tag {
ret = 1,
assign,
store,
oper,
};
  Tag tag;
  Stmt(Tag tag) : tag(tag) {}
};

struct StmtRetWrapper final : Stmt {
Ptr<Value> v;
 StmtRetWrapper() : Stmt(Tag::ret) {}
};

struct StmtAssignWrapper final : Stmt {
String x;
Ptr<Expr> e;
 StmtAssignWrapper() : Stmt(Tag::assign) {}
};

struct StmtStoreWrapper final : Stmt {
Ptr<Access> dst;
Ptr<NKIOperator> op;
List<Ptr<Value>> args;
 StmtStoreWrapper() : Stmt(Tag::store) {}
};

struct StmtOperWrapper final : Stmt {
Ptr<NKIOperator> op;
 StmtOperWrapper() : Stmt(Tag::oper) {}
};

struct Kernel final {
  String name;
  List<Ptr<TensorName>> inputs;
  List<Ptr<TensorName>> outputs;
  List<Ptr<Stmt>> body;
};

struct Operand {
enum class Tag {
imm = 1,
tile,
};
  Tag tag;
  Operand(Tag tag) : tag(tag) {}
};

struct OperandImmWrapper final : Operand {
Ptr<Immediate> i;
 OperandImmWrapper() : Operand(Tag::imm) {}
};

struct OperandTileWrapper final : Operand {
Ptr<TensorRef> t;
 OperandTileWrapper() : Operand(Tag::tile) {}
};













struct KLRFile final {
  Nat major;
  Nat minor;
  Nat patch;
};

struct KLRMetaData final {
  String format;
};

struct Contents {
enum class Tag {
python = 1,
nki,
klir,
hlo,
};
  Tag tag;
  Contents(Tag tag) : tag(tag) {}
};

struct ContentsPythonWrapper final : Contents {
Ptr<Kernel> kernel;
 ContentsPythonWrapper() : Contents(Tag::python) {}
};

struct ContentsNkiWrapper final : Contents {
Ptr<Kernel> kernel;
 ContentsNkiWrapper() : Contents(Tag::nki) {}
};

struct ContentsKlirWrapper final : Contents {
Ptr<Kernel> kernel;
 ContentsKlirWrapper() : Contents(Tag::klir) {}
};

struct ContentsHloWrapper final : Contents {
String name;
 ContentsHloWrapper() : Contents(Tag::hlo) {}
};
}
